2018-04-15 15:17:42,606 - __main__ - ERROR - Login attempt to from IP 
2018-04-15 15:20:32 - __main__ - ERROR - Login attempt to from IP 
2018-04-15 15:21:25 - __main__ - ERROR - Login attempt to from IP 
2018-04-15 15:22:18,22S - __main__ - ERROR - Login attempt to from IP 
2018-04-15 15:22:55.%f - __main__ - ERROR - Login attempt to from IP 
2018-04-15 15:23:03.2018-04-15 - __main__ - ERROR - Login attempt to from IP 
20180415152405%f - __main__ - ERROR - Login attempt to from IP 
%(msecs)03d - __main__ - ERROR - Login attempt to from IP 
2018-04-15 15:25:52.802 - __main__ - ERROR - Login attempt to from IP 
2018-04-15 15:27:27.029 - __main__ - ERROR - Login attempt to from IP 
2018-04-15 15:27:32.801 - Logger - ERROR - Login attempt to from IP 
2018-04-15 15:35:49.068 - Logger - ERROR - Login attempt to from IP 
2018-04-15 15:36:18.683 - Logger - ERROR - Login attempt to from IP 
2018-04-15 15:36:34.753 - Logger - ERROR - Login attempt to from IP 
2018-04-15 15:39:06.623 - Logger - ERROR - Login attempt to from IP 
2018-04-15 15:40:06.323 - Logger - ERROR - Login attempt to from IP 
2018-04-15 15:42:57.456 - Logger - ERROR - Login attempt to from IP 
2018-04-15 15:43:09.153 - Logger - ERROR - Login attempt to from IP 
2018-04-15 15:44:15.898 - Logger - ERROR - Login attempt to from IP 
2018-04-15 16:25:29.040 - Aerospike_Connect - ERROR MESSAGE: Failed to connect to the cluster with [('172.28.128.3', 3000)](-10, 'Failed to connect', 'src/main/aerospike/as_cluster.c', 249, False)
